name: Continuous Deployment
on: [push]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
              uses: actions/checkout@v2
            - name: Setup NodeJs
              uses: actions/setup-node@v1
              with:
               node-version: [10.x, 12.x, 14.x]
            - run: npm install -g surge
            - run: surge ./ ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }} 
